### ISSUE TITLE
nginx-proxy network create in compose?

### ISSUE THREAD

**Issue by frostyandy2k** [ekkis/nginx-proxy-LE-docker-compose#1]
Hi, first of, this project is amazing, thank you for putting in the work!

I have a question, why can't we create the network in the docker-compose file for nginx and need to create it via the docker network create command?

```
docker network create --subnet=172.28.0.0/16 --opt com.docker.network.bridge.name=nginx-proxy nginx-proxy
```
Is there a problem with the naming or the way compose creates networks?

**Comment by ekkis** [comment]
the reason is primarily that you’ll want to share the same network across docker-compose files.  so you can keep your services in one docker-compose file and the nginx services in another one but they get to share networks

**Comment by frostyandy2k** [comment]
AFAIK that scenario is also possible by using the following snippet in the docker-compose where nginx is running
```
networks:
   nginx-proxy:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.28.0.0/16
```
Source: https://docs.docker.com/compose/compose-file/#ipv4address-ipv6address
